### ISSUE TITLE
Allow usage of avy instead of ace-jump

### ISSUE THREAD

**Issue by ranulf** [tam17aki/ace-isearch#17]
As ace-jump-mode appears to be unmaintained it would be great if ace-isearch would support https://github.com/abo-abo/avy as a jump backend. From a user perspecitve avy works almost identical to ace-jump, except shows shows multi-character hints directly, where ace-jump shows them in sequence.

**Comment by tam17aki** [comment]
Thank you very much for using ace-isearch and your suggestion.
I will try to implement it.
If succeeded, I might release the new 'avy-version' as the new package (avy-isearch or something?).

Best regards,
Akira

**Comment by tam17aki** [comment]
Hi,

I tried to implement it.
Please try the latest version.

```
(setq ace-isearch-function 'avy-goto-char)
```

Best regards,
Akira Tamamori

**Comment by zeltak** [comment]
Thx for the avy integration, its wonderful!

best

Z

**Comment by ranulf** [comment]
Whoa - mind-blown! Thanks a ton for implementing it so fast!
Works like charm!
