### ISSUE TITLE
lazy highlighting doesn't dissapears in Emacs 25.1

### ISSUE THREAD

**Issue by ferfebles** [tam17aki/ace-isearch#25]
First, thank you very much for your package.

I'm using windows. With Emacs 25.1, during the search the matched words are highlighted, and after exiting the search they keep highlighted. If I execute 'lazy-highlight-cleanup' the highligh dissapears.

It doesn't happens in Emacs 24.

I tried to add a hook to isearch-mode-end-hook to execute 'lazy-highlight-cleanup, but it didn't work.'

This package is so useful that I prefer to stay in Emacs 24, but eventually I'll be forced to upgrade.

Any idea to why this is happening?

**Comment by ferfebles** [comment]
More tests: it doesn't happen with isearch, only with 'avy-goto-word-1' and 'ace-isearch-helm-swoop-from-isearch'

**Comment by tam17aki** [comment]
Hi,

Thank you for using the package.
I know the problem you pointed out, on Emacs 25.1.
Unfortunately, I am not sure how to solve it, for now.
If you find any solution, please let me know.
Pull-req is also welcome.
Also I will try to use lazy-highlight-cleanup, and investigate the problem.

Best regards,
Akira

**Comment by tam17aki** [comment]
The problem may be in isearch-update().
In emacs 24.5, 
```Lisp
  (when isearch-lazy-highlight
    (isearch-lazy-highlight-new-loop))
```
is executed before invoking ``` (run-hooks 'isearch-update-post-hook)```
On the other hand, in emacs 25.1, 
``` Lisp
(when isearch-lazy-highlight ...)
```
is executed after invoking ` isearch-update-post-hook`.

I am not sure this is a cause...

**Comment by tam17aki** [comment]
Therefore, simply adding `(setq isearch-lazy-highlight nil)` after `(funcall ace-isearch-function ...)` wii solve the problem.
