### ISSUE TITLE
helm-swoop seems to be unmaintained; consider helm-occur (optionally or permanently)

### ISSUE THREAD

**Issue by akater** [tam17aki/ace-isearch#31]
A recent update in helm made helm-swoop unusable. The patch have been proposed and tested yet not merged into melpa as of now.

Users discuss relative merits of helm-occur vs helm-swoop in the corresponding thread:
https://github.com/ShingoFukuyama/helm-swoop/issues/123#issuecomment-362799966

It might be worthwhile to consider helm-occur as an option (blind suggestion, I never used it yet) instead, or even as a permanent replacement for helm-swoop.

**Comment by tam17aki** [comment]
Hi,

Thank you for the information and suggestion.
Now I am considering this issue and will decide a plan.

**Comment by akater** [comment]
After long weeks of being broken, melpa's helm-swoop is functional
again. The issue may still be relevant though.

**Comment by sprig** [comment]
Personally, despite the maintenance status of helm-swoop, I find it to be far superior to helm-occur since it allows one to quickly go between candidates in the file.

**Comment by tam17aki** [comment]
Now the package supports helm-occur.

**Comment by tam17aki** [comment]
Thank you very much for the discussion.
