### ISSUE TITLE
How integrate with evil mode?

### ISSUE THREAD

**Issue by larebsyed** [tam17aki/ace-isearch#33]
evil mode has similar search functionality that is invoked with "/" key. But string length doesn't leads to change in search method

**Comment by larebsyed** [comment]
@tam17aki Any update on this?

**Comment by tam17aki** [comment]
Unfortunately not yet.

It seems that evil-mode turns `isearch-regexp` into t, when using the search functionality invoked by "/" key.
However, ace-isearch keeps silent if the `isearch-regexp` is t.

**Comment by larebsyed** [comment]
oh right, can I help you on this? I am not sure where to start but does it mean that ace-isearch will not work or regex search?

**Comment by tam17aki** [comment]
As I mentioned, ace-isearch will not be invoked when using regex search.
When using the normal isearch, ace-isearch will be invoked.
This is the intended design.

If you hope to use the functionality of ace-isearch with evil-mode, I think you should modify `ace-isearch--jumper-function`, the core of ace-isearch.
Unfortunately, I'm not sure how to do it for now...
