### ISSUE TITLE
Bug in ace-isearch-helm-swoop-from-isearch with helm-swoop

### ISSUE THREAD

**Issue by tofgarion** [tam17aki/ace-isearch#39]
Hello,

There is a bug in `ace-isearch-helm-swoop-from-isearch` : the`helm-swoop` call should use `:query` instead of `:$query`. I have just sent a pull request solving the problem (not too difficult :)), see #38.

Best,

Christophe

**Comment by tam17aki** [comment]
I have updated the code to fix the bug, so I close this issue.

Thank you very much!

Akira

**Comment by tofgarion** [comment]
No problem, thanks for ace-isearch!

Best,

Christophe
