### ISSUE TITLE
I got a compiling err after install ace-isearch from MELPA

### ISSUE THREAD

**Issue by hick** [tam17aki/ace-isearch#7]
Compiling file d:/Program/Emacs/home/.emacs.d/elpa/ace-isearch-20150105.2145/ace-isearch.el at Fri Jan  9 14:38:15 2015
ace-isearch.el:51:1:Error: Wrong type argument: listp, :before

and it came out after adding "(global-ace-isearch-mode +1)" in ".emacs"  and restarting emacs

**Comment by hick** [comment]
BTW platform windows7 + emacs 24.4

**Comment by tam17aki** [comment]
Hi Hick,

Thank you for using ace-isearch and reporting the compilation problem.
Unfortunately my platform is Emacs 24.4 on Mac OS X, so I can't reproduce it immediately...

Anyway, please let me confirm:
Are you using the latest version of ace-jump-mode and helm-swoop, respectively?

**Comment by tam17aki** [comment]
I mean, I want to confirm whether or not any other old versions of ace-jump-mode and helm-swoop are still being left.

**Comment by hick** [comment]
it seems like they are the latest,  and you can get more detail about the debug trace in one picture I uploaded.   
![ace-isearch](https://cloud.githubusercontent.com/assets/38886/5678440/74721fd0-982d-11e4-974c-33f5bce65f52.png)

![ace-isearch](https://cloud.githubusercontent.com/assets/38886/5678410/1c59ffb6-982d-11e4-90fc-6bdb945248a9.jpg)

**Comment by hick** [comment]
not at all,  and it's me that should say thanks to u  :)

I've not installed any package like   "helm-*"( including helm) manually but automatically...so, I've no settings about helm, I just heard about helm something like "ido", and have a plan to learn about it.

My .emacs is in https://github.com/hick/emacs/tree/master/,  ignoring the "init-local.el" which is for testing purpose.

as you mentioned about helm, I upgraded all package, and it does not change anything,  or maybe I should have some setting for helm? 

thanks

**Comment by hick** [comment]
I do not know why, but indeed, after some time , everything goes well!  
now I am using ace-isearch almost everyday well.
thx 2 Akira  :)
