### ISSUE TITLE
Work weird with isearch

### ISSUE THREAD

**Issue by wd** [tam17aki/ace-isearch#8]
```elisp
(define-key isearch-mode-map (kbd "C-f") 
  '(lambda ()
     (interactive)
     (save-excursion
       (set 'ps (re-search-backward "[^[:alnum:]-_@.]" nil t))
       (forward-char)
       (isearch-yank-internal
        (lambda ()
          (set 'pe (re-search-forward "[[:alnum:]-_@.]*[[:alnum:]]" nil t))
          (kill-ring-save (+ ps 1) pe)
          (+ pe 0)
          )
        ))
     )
  )
```

I usually use C-s C-f to yank current symbol to isearch, ace-isearch will trigger helm-swoop, when I select one founded line and press RET, helm-swoop will quit, but the cursor won't goto that line. Do not know where am wrong ..

**Comment by tam17aki** [comment]
Hi,

Thank you for using ace-isearch.

If you are using Emacs 24.4, you can try `isearch-forward-symbol-at-point` which implements the same feature as you intended:
```el:
(define-key isearch-mode-map (kbd "C-f") 'isearch-forward-symbol-at-point)
```
Using this command, cursor go to the line properly.
I can't point out what is wrong about your snippet for now...

**Comment by wd** [comment]
Thanks, it's workd. :+1:
